=== Enoxen/JWD_XML_Parsers-Task_3.3/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.xml.tc/gem"
        xmlns:tns="http://www.xml.tc/gem">

    <element name="gems">
        <complexType>
            <sequence>
                <element name="gem" type="tns:Gem" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="Gem">
        <attribute name="id" type="int" use="required"/>
        <sequence>
            <element name="name" type="string"/>
            <element name="preciousness" type="string"/>
            <element name="visualParameters" type="tns:Visual"/>
            <element name="value" type="positiveInteger"/>
        </sequence>
    </complexType>
    <complexType name="Visual">
        <sequence>
            <element name="color" type="string"/>
            <element name="shine" type="string"/>
            <element name="transparency" type="string"/>
        </sequence>
    </complexType>

</schema>

=== Enoxen/JWD_XML_Parsers-Task_3.3/src/main/resources/myXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:gems xmlns:tc="http://www.xml.tc/gem"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.xml.tc/gem config.xsd"
>
    <gem id="1">
        <name>Алмаз</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Бесцветный</color>
            <shine>Алмазный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>10</value>
    </gem>
    <gem id="2">
        <name>Рубин</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>15</value>
    </gem>
    <gem id="3">
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Фиолетовый</color>
            <shine>Стеклянный, перламутровый</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>9</value>
    </gem>
    <gem id="4">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="5">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="6">
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Фиолетовый</color>
            <shine>Стеклянный, перламутровый</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>9</value>
    </gem>
    <gem id="7">
        <name>Рубин</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>15</value>
    </gem>
    <gem id="8">
        <name>Алмаз</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Бесцветный</color>
            <shine>Алмазный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>10</value>
    </gem>
    <gem id="9">
        <name>Рубин</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>15</value>
    </gem>
    <gem id="10">
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Фиолетовый</color>
            <shine>Стеклянный, перламутровый</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>9</value>
    </gem>
    <gem id="11">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="12">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="13">
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Фиолетовый</color>
            <shine>Стеклянный, перламутровый</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>9</value>
    </gem>
    <gem id="14">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="15">
        <name>Гранат</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>14</value>
    </gem>
    <gem id="16">
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <visualParameters>
            <color>Фиолетовый</color>
            <shine>Стеклянный, перламутровый</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>9</value>
    </gem>
    <gem id="17">
        <name>Алмаз</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Бесцветный</color>
            <shine>Алмазный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>10</value>
    </gem>
    <gem id="18">
        <name>Рубин</name>
        <preciousness>Драгоценный</preciousness>
        <visualParameters>
            <color>Красный</color>
            <shine>Стеклянный</shine>
            <transparency>Прозрачный</transparency>
        </visualParameters>
        <value>15</value>
    </gem>
</tc:gems>
